package toodles.com.za.work.model;

import java.io.Serializable;

/**
 * Created by smoit on 2017/02/25.
 */

public class OrderDescr implements Serializable {


    /* (IN XORDERID INT(10),IN XCUSTID INT(10),IN XITEMID INT(10),
									  IN XEXTRASID INT(10),IN XREMOVEDID INT(10), IN XPRICE DOUBLE, IN XPARENTIND VARCHAR(10),
                                      IN XCARTID INT(10),IN PARENTID INT(10),IN XAPPTOKEN VARCHAR(9999))*/
    public static final String ORDER_ID = "XORDERID";
    public static final String CUST_ID = "XCUSTID";
    public static final String ITEM_ID = "XITEMID";
    public static final String EXTRAS_ID = "XEXTRASID";
    public static final String REMOVED_ID = "XREMOVEDID";
    public static final String PRICE = "XPRICE";
    public static final String CART_POSITION = "XCARTID";
    public static final String PARENT_ID = "PARENTID";
    public static final String PARENT_IND = "XPARENTIND";
    public static final String APP_TOKEN = "XAPPTOKEN";
    public static final String ADDED_ITEMS_TOTAL = "XADDED_ITEMS_TOT";


    private int orderid; //This orderid will be generated by the system when order is place, at initialization we will pass 0
    private int custormerID; //This wil be stored in the app shared preferences
    private int itemID;
    private int extrasID; //Only if extras have been added
    private int removedID; //Only if there are items removed
    private double price;
    private double addedItemsTotal;
    private int cartPosition;
    private int parentID;
    private char parentIND;
    private String appToken;

    public String getAppToken() {
        return appToken;
    }

    public void setAppToken(String appToken) {
        this.appToken = appToken;
    }

    public OrderDescr() {
    }

    public OrderDescr(int orderid, int custormerID, int itemID, int extrasID, int removedID, double price, int cartPosition, int parentID, char parentIND, String appToken) {
        this.orderid = orderid;
        this.custormerID = custormerID;
        this.itemID = itemID;
        this.extrasID = extrasID;
        this.removedID = removedID;
        this.price = price;
        double addedItemsTotal;
        this.cartPosition = cartPosition;
        this.parentID = parentID;
        this.parentIND = parentIND;
        this.appToken = appToken;
    }

    public int getOrderid() {
        return orderid;
    }

    public void setOrderid(int orderid) {
        this.orderid = orderid;
    }

    public int getCustormerID() {
        return custormerID;
    }

    public void setCustormerID(int custormerID) {
        this.custormerID = custormerID;
    }

    public int getItemID() {
        return itemID;
    }

    public void setItemID(int itemID) {
        this.itemID = itemID;
    }

    public int getExtrasID() {
        return extrasID;
    }

    public void setExtrasID(int extrasID) {
        this.extrasID = extrasID;
    }

    public int getRemovedID() {
        return removedID;
    }

    public void setRemovedID(int removedID) {
        this.removedID = removedID;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public double getAddedItemsTotal() {
        return addedItemsTotal;
    }

    public void setAddedItemsTotal(double addedItemsTotal) {
        this.addedItemsTotal = addedItemsTotal;
    }

    public int getCartPosition() {
        return cartPosition;
    }

    public void setCartPosition(int cartPosition) {
        this.cartPosition = cartPosition;
    }

    public int getParentID() {
        return parentID;
    }

    @Override
    public String toString() {
        return "OrderDescr{" +
                "orderid=" + orderid +
                ", custormerID=" + custormerID +
                ", itemID=" + itemID +
                ", extrasID=" + extrasID +
                ", removedID=" + removedID +
                ", price=" + price +
                ", addedItemsTotal=" + addedItemsTotal +
                ", cartPosition=" + cartPosition +
                ", parentID=" + parentID +
                ", parentIND=" + parentIND +
                ", appToken='" + appToken + '\'' +
                '}';
    }

    public void setParentID(int parentID) {
        this.parentID = parentID;
    }

    public char getParentIND() {
        return parentIND;
    }

    public void setParentIND(char parentIND) {
        this.parentIND = parentIND;
    }


}
